### ISSUE TITLE
Three dlls should be copied to the base directory of the package on windows

### ISSUE THREAD

**Issue by mattip** [conda-forge/pypy3.6-feedstock#101]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

xref conda-forge/miniforge#385. Running the package on windows without adding the `Library/bin` directory to the path fails. That directory is added by activation, but the interpreter should run without requiring activation. The solution would be to copy `libbz2.dll`, `libexpat.dll`, `ffi-8.dll` into the base directory during the build.

### Installed packages

```shell
not relevant
```

### Environment info

```shell
not relevant
```

**Comment by isuruf** [comment]
That would have been an option if symlinks worked, but they don't on windows without elevated permissions.
I'm not sure how to fix this.

**Comment by isuruf** [comment]
Maybe https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/3e82b658-e070-4b88-aaf2-0649ddb222d2/how-to-write-manifest-file-to-pick-up-dlls-via-dll-redirection?forum=vcgeneral

**Comment by mattip** [comment]
Can we add a copy command [here](https://github.com/conda-forge/pypy3.6-feedstock/blob/main/recipe/bld.bat#L44) in the script?

**Comment by isuruf** [comment]
No, then pypy will be using the DLLs that were used at build time and not the updated DLLs

**Comment by mattip** [comment]
OK. `zlib.dll` is already there, is that a bug?

BTW, I am working on getting `os.symlink`, `os.readlink` to work on windows + PyPy, but this will only be in the next release.

**Comment by isuruf** [comment]
> zlib.dll is already there, is that a bug?

Not really. It's in the zlib package itself. We added it because it's a tiny DLL. expat, ffi on the hand are not.

**Comment by mattip** [comment]
Here is what the base directory looks like after copying the three dlls. I am not sure those three add all that much. There is the security problem that once copied, they become part of the release so updating any of them requires updating the feedstock. I think the last few times I saw a problem with libexpat or libbz2 the fixes required recompiling python anyway, so I am not sure how concerning security considerations are.

```
>dir d:\miniconda\envs\pypy\*.dll
06/05/2022  17:21            21,984 api-ms-win-core-console-l1-1-0.dll
06/05/2022  17:29            21,976 api-ms-win-core-console-l1-2-0.dll
06/05/2022  17:21            21,984 api-ms-win-core-datetime-l1-1-0.dll
06/05/2022  17:21            21,984 api-ms-win-core-debug-l1-1-0.dll
06/05/2022  17:21            21,976 api-ms-win-core-errorhandling-l1-1-0.dll
06/05/2022  17:21            21,992 api-ms-win-core-fibers-l1-1-0.dll
06/05/2022  17:21            26,088 api-ms-win-core-file-l1-1-0.dll
06/05/2022  17:21            21,976 api-ms-win-core-file-l1-2-0.dll
06/05/2022  17:22            21,976 api-ms-win-core-file-l2-1-0.dll
06/05/2022  17:21            21,984 api-ms-win-core-handle-l1-1-0.dll
06/05/2022  17:21            21,984 api-ms-win-core-heap-l1-1-0.dll
06/05/2022  17:21            21,984 api-ms-win-core-interlocked-l1-1-0.dll
06/05/2022  17:22            22,008 api-ms-win-core-libraryloader-l1-1-0.dll
06/05/2022  17:21            21,984 api-ms-win-core-localization-l1-2-0.dll
06/05/2022  17:21            21,976 api-ms-win-core-memory-l1-1-0.dll
06/05/2022  17:21            21,984 api-ms-win-core-namedpipe-l1-1-0.dll
06/05/2022  17:21            22,008 api-ms-win-core-processenvironment-l1-1-0.dll
06/05/2022  17:21            21,976 api-ms-win-core-processthreads-l1-1-0.dll
06/05/2022  17:21            21,976 api-ms-win-core-processthreads-l1-1-1.dll
06/05/2022  17:21            21,992 api-ms-win-core-profile-l1-1-0.dll
06/05/2022  17:21            21,984 api-ms-win-core-rtlsupport-l1-1-0.dll
06/05/2022  17:21            21,976 api-ms-win-core-string-l1-1-0.dll
06/05/2022  17:21            21,976 api-ms-win-core-synch-l1-1-0.dll
06/05/2022  17:22            21,976 api-ms-win-core-synch-l1-2-0.dll
06/05/2022  17:21            21,984 api-ms-win-core-sysinfo-l1-1-0.dll
06/05/2022  17:21            21,976 api-ms-win-core-timezone-l1-1-0.dll
06/05/2022  17:21            21,992 api-ms-win-core-util-l1-1-0.dll
06/05/2022  17:21            21,984 api-ms-win-crt-conio-l1-1-0.dll
06/05/2022  17:21            26,080 api-ms-win-crt-convert-l1-1-0.dll
06/05/2022  17:21            21,984 api-ms-win-crt-environment-l1-1-0.dll
06/05/2022  17:21            21,984 api-ms-win-crt-filesystem-l1-1-0.dll
06/05/2022  17:21            21,984 api-ms-win-crt-heap-l1-1-0.dll
06/05/2022  17:21            21,984 api-ms-win-crt-locale-l1-1-0.dll
06/05/2022  17:21            30,184 api-ms-win-crt-math-l1-1-0.dll
06/05/2022  17:21            30,176 api-ms-win-crt-multibyte-l1-1-0.dll
06/05/2022  17:21            75,232 api-ms-win-crt-private-l1-1-0.dll
06/05/2022  17:21            21,984 api-ms-win-crt-process-l1-1-0.dll
06/05/2022  17:21            26,104 api-ms-win-crt-runtime-l1-1-0.dll
06/05/2022  17:21            26,080 api-ms-win-crt-stdio-l1-1-0.dll
06/05/2022  17:22            26,072 api-ms-win-crt-string-l1-1-0.dll
06/05/2022  17:21            21,984 api-ms-win-crt-time-l1-1-0.dll
06/05/2022  17:21            22,000 api-ms-win-crt-utility-l1-1-0.dll
12/01/2023  10:53           327,504 concrt140.dll
09/11/2021  22:16            25,600 ffi-8.dll
29/11/2020  01:13           187,904 libbz2.dll
25/10/2022  21:06           401,408 libexpat.dll
18/01/2023  19:13        43,297,280 libpypy3.9-c.dll
12/01/2023  10:53           579,920 msvcp140.dll
12/01/2023  10:53            35,664 msvcp140_1.dll
12/01/2023  10:53           197,456 msvcp140_2.dll
12/01/2023  10:53            50,000 msvcp140_atomic_wait.dll
12/01/2023  10:53            31,568 msvcp140_codecvt_ids.dll
06/05/2022  17:22         1,123,808 ucrtbase.dll
12/01/2023  10:53           414,544 vcamp140.dll
12/01/2023  10:53           345,936 vccorlib140.dll
12/01/2023  10:53           191,824 vcomp140.dll
12/01/2023  10:53           109,392 vcruntime140.dll
12/01/2023  10:53            49,488 vcruntime140_1.dll
14/10/2022  17:02            89,088 zlib.dll
```

**Comment by mattip** [comment]
Another option would be to load `libpypy*.dll` via `dlopen` in `pypy.exe`, and move the `add_dll_directory` code to run before that.

**Comment by mattip** [comment]
[Here](https://foss.heptapod.net/pypy/pypy/-/blob/branch/default/rpython/translator/platform/windows.py#L505) is the area in the code that would need to change to make `main()` load the libpypy dll dynamically.

**Comment by mattip** [comment]
I tried searching through CPython issues and history for why python.exe is statically linked to libpython.dll and if anyone had considered using dlopen() instead without much luck.

**Comment by mattip** [comment]
Looking at the [link](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/3e82b658-e070-4b88-aaf2-0649ddb222d2/how-to-write-manifest-file-to-pick-up-dlls-via-dll-redirection?forum=vcgeneral) above about adding manifests to allow searching other directories, I think the steps are:
- turn the dlls into an assembly by adding a `python.assembly.mainfest` file to the `Library/bin` directory with the content
```
<assembly manifestVersion="1.0">
  <assemblyIdentity type="Win32" name="python.assembly" version="1.0.0.0" processorArchitecture="x86" publicKeyToken="257fa66c876581b9"/>
 <file name="libbz2.dll" hashalg="SHA1"/>
 <file name="libexpat.dll" hashalg="SHA1"/>
 <file name="ffi-8.dll" hashalg="SHA1"/>
</assembly> 
```

- Get pypy-c.exe to load the assembly by recompiling it with this link option (from the article)
```
#pragma comment(linker,"/manifestdependency:\"type='win32' "\
  "name='python.assembly' "\
  "version='1.0.0.0' "\
  "processorArchitecture='*' "\
  "language='*' "\
  "\"") 
```

The source code for the exe (main.c) is one line:
```
int pypy_main_startup(int, char*[]); int main(int argc, char* argv[]) { return pypy_main_startup(argc, argv); }
```

and the commands to compile it is:
```
cl.exe /I<pypy-includes> main.c -o main.obj
link.exe /DEBUG /LARGEADDRESSAWARE /STACK:3145728 main.obj libpypy3.9-c.lib /out:pypy3.9-c.exe
```
I am not sure how that link option from the article would work here, would it be part of `main.c`?

- Once the `exe` is compiled to use the assembly, an appropriate `pypy3.9-c.exe.manifest` should be added to the directory with the `exe`, with the contents:
```
<configuration>
 <windows>
 <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
 <probing privatePath="Library/bin"/>
 </assemblyBinding>
 </windows>
</configuration>
```

Did I miss something?

**Comment by mattip** [comment]
@isuruf it seems a bit silly to implement this for these three DLLS when conda-forge copies about 50 runtime dlls into the base directory (as well as duplicating them for every environment into `Library/bin`

**Comment by karthiknadig** [comment]
This is affecting tools and extensions for VS Code, see : https://github.com/microsoft/vscode-isort/issues/291

**Comment by ndahn** [comment]
As @mattip commented, there are already a few dozen libraries copied into the main folder, and the ffi-8, bz2 and expat are about half a megabyte in total. For 99.999% of all systems this won't make a difference, and the rest will heavily optimize any installation anyways. 

I don't see why such a simple solution should be ignored. If there is ever an issue because of 3 duplicate files, you can still create some assembly or whatever 🙄
