### ISSUE TITLE
Unsupport PyPy on aarch64/ppc64le?

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/pypy3.6-feedstock#111]
We haven't built 7.3.12 or 7.3.13 on aarch/ppc, so those continue to bitrot and not receive relevant fixes. Given that it's a niche² usecase, and especially since we have no functional CI for it, I think the maintenance effort is completely out of whack with the provided utility.

FWIW, I'm in favour of supporting PyPy widely, but given the discussion (e.g. [here](https://github.com/conda-forge/pypy3.6-feedstock/issues/104)) of how tight maintenance is stretched on that already, I think it would be completely reasonable to just remove support on these platforms.

CC @conda-forge/pypy3-6 @conda-forge/pypy-meta @conda-forge/core

**Comment by mattip** [comment]
Makes sense to me. How can that be done?

**Comment by h-vetinari** [comment]
We'd should likely announce it, and then some time later, we could remove those arches from the pypy-migrator in the pinning repo; that'd mean all feedstocks with pypy would drop those builds upon rerendering.

**Comment by isuruf** [comment]
Since it'd be impossible bring them back once removed from the migrator and it's only this package, I can build these. Only have access to ppc64le atm though.

**Comment by mattip** [comment]
If conda-forge wishes, I can also build them. Last time I followed [this gist](https://gist.github.com/mattip/1cb3c04fe1c285f62dfb4884cc1c5f22). I have think I have access to both machines.

**Comment by h-vetinari** [comment]
> impossible bring them back once removed from the migrator

We could have a pypy on arch migrator like we had for windows, to reintroduce support whenever the situation improves. The manual builds are too much of a bottleneck IMO, especially looking at the miniscule download numbers.

**Comment by h-vetinari** [comment]
My point is: in the last core call that touched upon pypy support (in the context of https://github.com/conda-forge/pypy3.6-feedstock/issues/104), we were essentially ready to drop support if there's no-one from the upstream pypy devs that can help us. Given that those resources are extremely limited, would we rather spend them on broad pypy support (fixing issues with popular packages, migrating pypy3.10, etc.), or niche architectures with package downloads on the order of 1 per 10'000 users?

**Comment by h-vetinari** [comment]
I brought this up in the core meeting last week. Isuru preferred to keep the builds and offered to build for the arches.

Concretely, we're getting close to finally building grpcio for PyPy for the first time, and that means (as of status now) that all the packages dependent on that in the migration would fail on missing builds.

Can you please build 7.3.13, Isuru?

**Comment by mattip** [comment]
@isuruf I have uploaded the 7.3.13 builds to my [space at ananconda.org](https://anaconda.org/mattip/repo/files?type=any&label=copy). The logs are attached. Please copy them to the feedstock.
[aarch64_log.txt](https://github.com/conda-forge/pypy3.6-feedstock/files/12871511/aarch64_log.txt)
[ppc64le._log.txt](https://github.com/conda-forge/pypy3.6-feedstock/files/12871513/ppc64le._log.txt)

**Comment by isuruf** [comment]
Thanks @mattip. I've copied them over.

**Comment by mattip** [comment]
Closing for now.
