### ISSUE TITLE
Port patches from python-feedstock

### ISSUE THREAD

**Issue by isuruf** [conda-forge/pypy3.6-feedstock#15]
These patches need to be ported. Paths are different though. `Lib/distutils` in CPython is in `lib-pytho/3/lib/distutils`

https://github.com/conda-forge/python-feedstock/blob/master/recipe/patches/0009-runtime_library_dir_option-Use-1st-word-of-CC-as-com.patch
https://github.com/conda-forge/python-feedstock/blob/master/recipe/patches/0008-Darwin-Look-in-sysroot-usr-lib-include-if-sysroot-is.patch
https://github.com/conda-forge/python-feedstock/blob/master/recipe/patches/0021-roll-back-2e33ecd-for-py_compile.main.patch
https://github.com/conda-forge/python-feedstock/blob/master/recipe/patches/0012-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
https://github.com/conda-forge/python-feedstock/blob/master/recipe/patches/0013-Disable-new-dtags-in-unixccompiler.py.patch
https://github.com/conda-forge/python-feedstock/blob/master/recipe/patches/0020-Use-ranlib-from-env-if-env-variable-is-set.patch

cc @ocefpaf

**Comment by isuruf** [comment]
cc @mingwandroid

**Comment by ocefpaf** [comment]
- [X] https://github.com/conda-forge/python-feedstock/blob/master/recipe/patches/0009-runtime_library_dir_option-Use-1st-word-of-CC-as-com.patch

- [ ] https://github.com/conda-forge/python-feedstock/blob/master/recipe/patches/0008-Darwin-Look-in-sysroot-usr-lib-include-if-sysroot-is.patch

- [ ] https://github.com/conda-forge/python-feedstock/blob/master/recipe/patches/0021-roll-back-2e33ecd-for-py_compile.main.patch

- [ ] https://github.com/conda-forge/python-feedstock/blob/master/recipe/patches/0012-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch

- [ ] https://github.com/conda-forge/python-feedstock/blob/master/recipe/patches/0013-Disable-new-dtags-in-unixccompiler.py.patch

- [ ] https://github.com/conda-forge/python-feedstock/blob/master/recipe/patches/0020-Use-ranlib-from-env-if-env-variable-is-set.patch

**Comment by isuruf** [comment]
Thanks @ocefpaf
