### ISSUE TITLE
The _hashlib module is not available, falling back to a much slower implementation

### ISSUE THREAD

**Issue by isuruf** [conda-forge/pypy3.6-feedstock#21]
`/home/conda/feedstock_root/build_artifacts/pypy3.6_1586527511164/work/pypy3/lib-python/3/hashlib.py:173: RuntimeWarning: The _hashlib module is not available, falling back to a much slower implementation (No module named '_pypy_openssl')`

cc @mattip

**Comment by mattip** [comment]
i am  missing a bit of context here. After compilation you need to build the _ssl module. It requires pieces of the _ hashlib module, to bootstrap, which has a pure python implementation that is replaced by the _ssl one after it is built.

**Comment by isuruf** [comment]
Nvm, the path of `build_cffi_imports.py` changed and I removed it first thinking it wasn't needed, but added it back. Sorry about the noise
