### ISSUE TITLE
Link to blog post from the README

### ISSUE THREAD

**Issue by mattip** [conda-forge/pypy3.6-feedstock#23]
This repo features pretty highly when searching for "conda pypy". It might be nice to add a link to the blog post about using conda with PyPy for people who are a bit lost https://conda-forge.org/blog/posts/2020-03-10-pypy/

**Comment by mattip** [comment]
Also the directions on https://anaconda.org/conda-forge/pypy3.6 and https://anaconda.org/conda-forge/pypy3.5, which are among the top search results, seem to have older instructions, can those be updated as well?

**Comment by isuruf** [comment]
If the line at https://github.com/conda-forge/pypy3.6-feedstock/blob/master/recipe/meta.yaml#L74 is changed and rerendered, both will be fixed.
