### ISSUE TITLE
ppc64le issues in 7.3.2

### ISSUE THREAD

**Issue by isuruf** [conda-forge/pypy3.6-feedstock#28]
These look like JIT issues

https://travis-ci.com/github/conda-forge/scikit-learn-feedstock/jobs/394779868
https://travis-ci.com/github/conda-forge/conda-feedstock/jobs/394808993

cc @mattip

**Comment by mattip** [comment]
This seems correct to mark as broken. We do have a fix for one ppc issue but it will only be available in the next release (after the current 7.2.3). Thanks for marking it "broken". The next step is to re-render the failing scikit-learn-feedstock?

**Comment by isuruf** [comment]
I've restarted the travis-ci jobs for `conda-feedstock` and `scikit-learn-feedstock`

We can add the patch for the ppc issue to https://github.com/conda-forge/pypy3.6-feedstock/ to see if that fixes the issue. Can you point me to the commit that fixed the ppc issue?

**Comment by mattip** [comment]
[this](https://foss.heptapod.net/pypy/pypy/-/commit/913e0dae8ac7ce8219a5f31126fee8a794cc314c) is the fix, but [this fix to tests](https://foss.heptapod.net/pypy/pypy/-/commit/c9be894f9061834901e5be5199e6b8ad37263f9e) and [this other fix to tests](https://foss.heptapod.net/pypy/pypy/-/commit/525479ae05b62a3dba4513cae7d4b0c056686507) should also be part of the patch
