### ISSUE TITLE
PyPy 7.3.4 is released, but only for python3.7

### ISSUE THREAD

**Issue by mattip** [conda-forge/pypy3.6-feedstock#37]
PyPy is no longer releasing python3.6 versions. So to update the recipe here for the newest PyPy 7.3.4 will require reworking the `recipe/meta.yml`. Any ideas how to do this correctly?

The hash and source file is 
```
74d3c1e79f3fc7d384ffb32d3d2a95c2d5f61b81091eccce12ac76030d96ad08  pypy3.7-v7.3.4-src.tar.bz2
```

**Comment by isuruf** [comment]
Changing https://github.com/conda-forge/pypy3.6-feedstock/blob/f1f7da828bbd5cd83f2f7a1ba0066460b2a8550a/recipe/meta.yaml#L33 from `[win]` to `[win or name_suffix=="3.6"]`
