### ISSUE TITLE
PyPy3.8 windows failure

### ISSUE THREAD

**Issue by isuruf** [conda-forge/pypy3.6-feedstock#60]
The windows failure is because with python 3.8, PATH is not searched for dependent DLLs and the ctypes extension cannot find libffi-8.dll.

For CPython, our solution was to do `os.add_dll_directory(sys.prefix, "Library", "bin")` when the python interpreter is initialized. I'm not sure where that code should go to in PyPy though.

cc @mattip

**Comment by h-vetinari** [comment]
Fixed by #61.
