### ISSUE TITLE
add aarch64, ppc64le, s390x builds

### ISSUE THREAD

**Issue by mattip** [conda-forge/pypy3.6-feedstock#7]
Issue:
How can we add a .travis.yml file to install aarch64, ppc64le, s390x tarballs of pypy36 7.3? Travis supports those architectures.

**Comment by isuruf** [comment]
Travis only gives us 50 minutes which is not enough

**Comment by isuruf** [comment]
ppc64le build fail because it does not respect CC env variable. It's trying to use `gcc` from the system, but not $CC which comes from conda and fails.
https://gist.github.com/isuruf/8dcb35fb4f8145a1207ab23c230cfb00

**Comment by isuruf** [comment]
Looks like it is using `$CC=powerpc64le-conda_cos7-linux-gnu-gcc` for compiling, but `gcc` for linking.

**Comment by isuruf** [comment]
We have aarch64 and ppc64le builds thanks to machines provided by Works on Arm and OSU OSL.
conda-forge doesn't support s390x atm.

**Comment by mattip** [comment]
So the strategy is to independently build and upload the artifacts?

**Comment by isuruf** [comment]
Yes, I already uploaded ppc64le. aarch64 build hung at `make -j 32 in /tmp/usession-release-pypy3.7-v7.3.5rc3-0/testing_1` for hours. I killed it and trying again with 8 jobs.
