### ISSUE TITLE
openssl3 migration for pypy3.7

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/pypy3.6-feedstock#75]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I understand that pypy3.8 is around the corner, but some packages are being rebuilt for openssl and a branch is missing here to build out the packages for pypy and openssl3

### Installed packages

```shell
https://github.com/conda-forge/scrypt-feedstock/pull/37
```

### Environment info

```shell
https://github.com/conda-forge/scrypt-feedstock/pull/37
```

**Comment by hmaarrfk** [comment]
or at least, the packages for aarch and ppc64le are missing :/

**Comment by h-vetinari** [comment]
Should be solved for pypy3.8/3.9 now though. One the migration restarts (and gets to scrypt), it should hopefully be fine...

**Comment by mattip** [comment]
Since the latest migration dropped pypy3.7, I think we can close this? Please reopen if I am mistaken.
