### ISSUE TITLE
_sysconfigdata__*.py is not updated when the package is installed

### ISSUE THREAD

**Issue by mattip** [conda-forge/pypy3.6-feedstock#86]
The package to download has a `_sysconfigdata__*.py` file that captures the state at build time. This should be overwritten with information when the package is installed. For instance, the x86_64 downloaded package has 
`'INCLUDEPY': '/home/conda/feedstock_root/build_artifacts/pypy3.8_1658434607149/work/pypy3/include/pypy3.8'`
which is wrong once the package is installed. The CPython packages also have bogus paths, but these are somehow rewritten. The invocation to do this is 
`python -m sysconfig --generate-posix-vars`
Is that somehow run for CPython at installation but not for PyPy?

**Comment by isuruf** [comment]
We can try running that after installation.

**Comment by mattip** [comment]
thanks, I will try that out
