### ISSUE TITLE
Broken cross-compilation with latest build

### ISSUE THREAD

**Issue by xhochy** [conda-forge/pypy3.6-feedstock#90]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

With the last PR (https://github.com/conda-forge/pypy3.6-feedstock/pull/87) cross-compilation seems to be broken on linux-aarch64 (not linux-ppc64le though). The `cross-python` activation simply fails with the following output:

```
Setting up cross-python
ERROR: 'HOST_GNU_TYPE'
```

Running the activation using `bash -x`, I can see it breaks at the following line:

```
++++ /home/uwe/mambaforge/conda-bld/awscrt_1665480308769/_build_env/bin/python -m crossenv /home/uwe/mambaforge/conda-bld/awscrt_1665480308769/_h_env_placehold_placehold_placehold_placehold_placehold_plac
ehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python --sysroot /home/uwe/mambaforge/conda-bld/awscrt_16
65480308769/_build_env/aarch64-conda-linux-gnu/sysroot --without-pip /home/uwe/mambaforge/conda-bld/awscrt_1665480308769/_build_env/venv --sysconfigdata-file /home/uwe/mambaforge/conda-bld/awscrt_16654803
08769/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p
laceh/lib/pypy3.8/_sysconfigdata__linux_aarch64-linux-gnu.py --cc /home/uwe/mambaforge/conda-bld/awscrt_1665480308769/_build_env/bin/aarch64-conda-linux-gnu-cc --cxx c++
```

### Installed packages

```shell
pypy3.9:            7.3.9-h57c6639_4     conda-forge
```

### Environment info

```shell
-
```

**Comment by xhochy** [comment]
FYI @mattip

**Comment by mattip** [comment]
Breaking that line down it turns into
```
<path>/bin/python -m crossenv <other_path>/bin/python --sysroot <path>/aarch64-conda-linux-gnu/sysroot --without-pip <path>/venv --sysconfigdata-file <other_path>/lib/pypy3.8/_sysconfigdata__linux_aarch64-linux-gnu.py --cc <path>/bin/aarch64-conda-linux-gnu-cc --cxx c++
```

so it seems like the underlying package is [crossenv](https://github.com/benfogle/crossenv) - is that correct? I see it uses [`HOST_GNU_TYPE`](https://github.com/benfogle/crossenv/blob/5c3b53aa2989fc442194e144fac90464dd4b3086/crossenv/__init__.py#L323). I wonder how this worked up to [PR #96](https://github.com/benfogle/crossenv/pull/96).

**Comment by isuruf** [comment]
https://github.com/conda-forge/pypy3.6-feedstock/blob/main/recipe/build.sh#L124 has a typo. `host_gun_type` instead of `host_gnu_type`

**Comment by mattip** [comment]
OY. Good catch. And then the call which should have pushed HOST_GNU_TYPE into the sysconfigdata
```
pypy -m sysconfig --generate-posix-vars HOST_GNU_TYPE $host_gnu_type
```

is actually called with an empty argument, so the [special PyPy argument processing](https://foss.heptapod.net/pypy/pypy/-/blob/branch/py3.8/lib-python/3/sysconfig.py#L404) fails to set `HOST_GNU_TYPE`.
